# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageProcessingDlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(924, 688)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(30, 10, 861, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 351, 281))
        self.groupBox.setObjectName("groupBox")
        self.toolButton1_1 = QtWidgets.QToolButton(self.groupBox)
        self.toolButton1_1.setGeometry(QtCore.QRect(240, 250, 71, 21))
        self.toolButton1_1.setObjectName("toolButton1_1")
        self.label1_1 = QtWidgets.QLabel(self.groupBox)
        self.label1_1.setGeometry(QtCore.QRect(31, 34, 301, 211))
        self.label1_1.setText("")
        self.label1_1.setObjectName("label1_1")
        self.lineEdit1_1 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit1_1.setGeometry(QtCore.QRect(30, 250, 191, 21))
        self.lineEdit1_1.setObjectName("lineEdit1_1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 310, 351, 301))
        self.groupBox_2.setObjectName("groupBox_2")
        self.toolButton1_2 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton1_2.setGeometry(QtCore.QRect(240, 270, 71, 21))
        self.toolButton1_2.setObjectName("toolButton1_2")
        self.label1_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label1_2.setGeometry(QtCore.QRect(21, 34, 311, 221))
        self.label1_2.setText("")
        self.label1_2.setObjectName("label1_2")
        self.lineEdit1_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit1_2.setGeometry(QtCore.QRect(32, 270, 191, 21))
        self.lineEdit1_2.setObjectName("lineEdit1_2")
        self.pushButton1_1 = QtWidgets.QPushButton(self.tab)
        self.pushButton1_1.setGeometry(QtCore.QRect(730, 570, 101, 28))
        self.pushButton1_1.setObjectName("pushButton1_1")
        self.label1_img = QtWidgets.QLabel(self.tab)
        self.label1_img.setGeometry(QtCore.QRect(440, 160, 361, 261))
        self.label1_img.setText("")
        self.label1_img.setObjectName("label1_img")
        self.pushButton1_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton1_2.setGeometry(QtCore.QRect(600, 570, 93, 28))
        self.pushButton1_2.setObjectName("pushButton1_2")
        self.lineEdit1_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit1_3.setGeometry(QtCore.QRect(400, 570, 191, 21))
        self.lineEdit1_3.setObjectName("lineEdit1_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 20, 351, 281))
        self.groupBox_3.setObjectName("groupBox_3")
        self.toolButton2_1 = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton2_1.setGeometry(QtCore.QRect(240, 250, 71, 21))
        self.toolButton2_1.setObjectName("toolButton2_1")
        self.label2_1 = QtWidgets.QLabel(self.groupBox_3)
        self.label2_1.setGeometry(QtCore.QRect(31, 34, 301, 211))
        self.label2_1.setText("")
        self.label2_1.setObjectName("label2_1")
        self.lineEdit2_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit2_1.setGeometry(QtCore.QRect(32, 250, 191, 21))
        self.lineEdit2_1.setObjectName("lineEdit2_1")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 310, 351, 301))
        self.groupBox_4.setObjectName("groupBox_4")
        self.toolButton2_2 = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton2_2.setGeometry(QtCore.QRect(240, 270, 71, 21))
        self.toolButton2_2.setObjectName("toolButton2_2")
        self.label2_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label2_2.setGeometry(QtCore.QRect(21, 34, 311, 221))
        self.label2_2.setText("")
        self.label2_2.setObjectName("label2_2")
        self.lineEdit2_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit2_2.setGeometry(QtCore.QRect(32, 270, 191, 21))
        self.lineEdit2_2.setObjectName("lineEdit2_2")
        self.label2_img = QtWidgets.QLabel(self.tab_2)
        self.label2_img.setGeometry(QtCore.QRect(430, 130, 401, 271))
        self.label2_img.setText("")
        self.label2_img.setObjectName("label2_img")
        self.pushButton2_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton2_2.setGeometry(QtCore.QRect(620, 570, 93, 28))
        self.pushButton2_2.setObjectName("pushButton2_2")
        self.pushButton2_1 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton2_1.setGeometry(QtCore.QRect(740, 570, 93, 28))
        self.pushButton2_1.setObjectName("pushButton2_1")
        self.lineEdit2_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit2_3.setGeometry(QtCore.QRect(410, 570, 191, 21))
        self.lineEdit2_3.setObjectName("lineEdit2_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 20, 371, 591))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label3_1 = QtWidgets.QLabel(self.groupBox_5)
        self.label3_1.setGeometry(QtCore.QRect(31, 34, 321, 501))
        self.label3_1.setText("")
        self.label3_1.setObjectName("label3_1")
        self.lineEdit3_1 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit3_1.setGeometry(QtCore.QRect(40, 560, 221, 21))
        self.lineEdit3_1.setObjectName("lineEdit3_1")
        self.toolButton3 = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton3.setGeometry(QtCore.QRect(290, 560, 47, 21))
        self.toolButton3.setObjectName("toolButton3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(430, 20, 411, 591))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label3_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label3_2.setGeometry(QtCore.QRect(31, 64, 361, 451))
        self.label3_2.setText("")
        self.label3_2.setObjectName("label3_2")
        self.pushButton3_1 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton3_1.setGeometry(QtCore.QRect(290, 550, 93, 28))
        self.pushButton3_1.setObjectName("pushButton3_1")
        self.pushButton3_2 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton3_2.setGeometry(QtCore.QRect(180, 550, 93, 28))
        self.pushButton3_2.setObjectName("pushButton3_2")
        self.lineEdit3_2 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit3_2.setGeometry(QtCore.QRect(10, 550, 161, 21))
        self.lineEdit3_2.setObjectName("lineEdit3_2")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_6)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 20, 341, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_7.setGeometry(QtCore.QRect(420, 20, 411, 591))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label4_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label4_2.setGeometry(QtCore.QRect(40, 30, 321, 501))
        self.label4_2.setText("")
        self.label4_2.setObjectName("label4_2")
        self.pushButton4_1 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton4_1.setGeometry(QtCore.QRect(310, 550, 93, 28))
        self.pushButton4_1.setObjectName("pushButton4_1")
        self.pushButton4_2 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton4_2.setGeometry(QtCore.QRect(200, 550, 93, 28))
        self.pushButton4_2.setObjectName("pushButton4_2")
        self.lineEdit4_2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit4_2.setGeometry(QtCore.QRect(10, 550, 181, 21))
        self.lineEdit4_2.setObjectName("lineEdit4_2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 20, 371, 591))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label4_1 = QtWidgets.QLabel(self.groupBox_8)
        self.label4_1.setGeometry(QtCore.QRect(31, 34, 321, 501))
        self.label4_1.setText("")
        self.label4_1.setObjectName("label4_1")
        self.lineEdit4_1 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit4_1.setGeometry(QtCore.QRect(40, 560, 221, 21))
        self.lineEdit4_1.setObjectName("lineEdit4_1")
        self.toolButton4 = QtWidgets.QToolButton(self.groupBox_8)
        self.toolButton4.setGeometry(QtCore.QRect(290, 560, 47, 21))
        self.toolButton4.setObjectName("toolButton4")
        self.tabWidget.addTab(self.tab_4, "")

        # 响应函数
        # 图像融合
        self.toolButton1_1.clicked.connect(Dialog.openimage1_1)
        self.toolButton1_2.clicked.connect(Dialog.openimage1_2)
        self.pushButton1_1.clicked.connect(Dialog.Fusion)
        self.pushButton1_2.clicked.connect(Dialog.saveimage1)

        # 图像镶嵌
        self.toolButton2_1.clicked.connect(Dialog.openimage2_1)
        self.toolButton2_2.clicked.connect(Dialog.openimage2_2)
        self.pushButton2_1.clicked.connect(Dialog.Mosaic)
        self.pushButton2_2.clicked.connect(Dialog.saveimage2)

        # 边缘检测
        self.toolButton3.clicked.connect(Dialog.openimage3)
        self.pushButton3_1.clicked.connect(Dialog.Canny)
        self.pushButton3_2.clicked.connect(Dialog.saveimage3)
        # 滑动条设置
        # 设置最小值
        self.horizontalSlider.setMinimum(0)
        # 设置最大值
        self.horizontalSlider.setMaximum(100)
        # 步长
        self.horizontalSlider.setSingleStep(10)
        # 设置当前值
        self.horizontalSlider.setValue(0)
        # 刻度位置，刻度下方
        self.horizontalSlider.setTickPosition(QSlider.TicksBelow)
        # 设置刻度间距
        self.horizontalSlider.setTickInterval(10)
        # 设置连接信号槽函数
        self.horizontalSlider.valueChanged.connect(Dialog.Canny)

        # 图像阴影检测
        self.toolButton4.clicked.connect(Dialog.openimage4)
        self.pushButton4_2.clicked.connect(Dialog.saveimage4)
        self.pushButton4_1.clicked.connect(Dialog.Getshadow)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "输入彩色图像"))
        self.toolButton1_1.setText(_translate("Dialog", "..."))
        self.groupBox_2.setTitle(_translate("Dialog", "输入灰度图像"))
        self.toolButton1_2.setText(_translate("Dialog", "..."))
        self.pushButton1_1.setText(_translate("Dialog", "运行"))
        self.pushButton1_2.setText(_translate("Dialog", "保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "图像融合"))
        self.groupBox_3.setTitle(_translate("Dialog", "输入图像1"))
        self.toolButton2_1.setText(_translate("Dialog", "..."))
        self.groupBox_4.setTitle(_translate("Dialog", "输入图像2"))
        self.toolButton2_2.setText(_translate("Dialog", "..."))
        self.pushButton2_2.setText(_translate("Dialog", "保存"))
        self.pushButton2_1.setText(_translate("Dialog", "运行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "图像镶嵌"))
        self.groupBox_5.setTitle(_translate("Dialog", "输入图像"))
        self.toolButton3.setText(_translate("Dialog", "..."))
        self.groupBox_6.setTitle(_translate("Dialog", "输出结果"))
        self.pushButton3_1.setText(_translate("Dialog", "运行"))
        self.pushButton3_2.setText(_translate("Dialog", "保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "边缘检测"))
        self.groupBox_7.setTitle(_translate("Dialog", "输出结果"))
        self.pushButton4_1.setText(_translate("Dialog", "运行"))
        self.pushButton4_2.setText(_translate("Dialog", "保存"))
        self.groupBox_8.setTitle(_translate("Dialog", "输入图像"))
        self.toolButton4.setText(_translate("Dialog", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "阴影检测"))
